/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/result/$id': typeof ResultIdRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AdminRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/result/$id': typeof ResultIdRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AdminRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/result/$id': typeof ResultIdRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AdminRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/connect'
    | '/dashboard'
    | '/insights'
    | '/profile'
    | '/result/$id'
    | '/auth'
    | '/pricing'
    | '/admin'
    | '/terms'
    | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/connect'
    | '/dashboard'
    | '/insights'
    | '/profile'
    | '/result/$id'
    | '/auth'
    | '/pricing'
    | '/admin'
    | '/terms'
    | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/connect'
    | '/dashboard'
    | '/insights'
    | '/profile'
    | '/result/$id'
    | '/auth'
    | '/pricing'
    | '/admin'
    | '/terms'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  ProfileRoute: typeof ProfileRoute
  ResultIdRoute: typeof ResultIdRoute
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  AdminRoute: typeof AdminRoute
  TermsRoute: typeof TermsRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  ProfileRoute: ProfileRoute,
  ResultIdRoute: ResultIdRoute,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  AdminRoute: AdminRoute,
  TermsRoute: TermsRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
